# Generated by Django 4.2.6 on 2023-11-26 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_mini_steam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('developer', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=50)),
                ('release_date', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.DeleteModel(
            name='Jogo',
        ),
    ]
